name: ZeroAuth

services:
  bot:
    build:
      context: .
      target: runner
    volumes:
      - type: bind
        source: ./config.py
        target: /app/config.py
        read_only: true
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - ./requirements.txt
            - ./.git
        - action: rebuild
          path: ./requirements.txt
